config/routes.rb
Rails.application.routes.draw do

  get 'locations/get_address'

  devise_for :users, skip: [:sessions, :registrations]

  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
    get    "users"   => "devise/registrations#edit",   as: :user_root
  end

  namespace :admin do
    get '/', to: 'pages#index'

    resources :products
    resources :users
    resources :orders, only: [:index, :show, :destroy]

  end

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create] do
      member do
        get 'like'
      end
    end

    member do
      get 'like'
      get 'add_to_cart'
    end
  end

  get 'cart', to: 'carts#show', as: 'cart'
  delete 'cart/:id', to: 'carts#destroy'

  get 'order', to: 'orders#create_order', as: 'create_order'
  get 'order/:id', to: 'orders#show', as: 'order'
  post 'order/:id', to: 'orders#paid_order', as: 'paid_order'
  delete 'order/:id', to: 'orders#cancel_order', as: 'cancel_order'

  get 'get_address', to: 'locations#get_address'

  root 'products#index'

end

app/views/shared/_admin_navbar.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <div class="container">
    <a class="navbar-brand" href="/">SuperStore</a>
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/admin">Admin <span class="sr-only">(current)</span></a>
      </li>
      <% if user_signed_in? && current_user.admin? %>
        <li class="nav-item">
          <a class="nav-link" href="/admin/products">Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/admin/orders">Orders</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/admin/users">Users</a>
        </li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav pull-right">
      <% unless user_signed_in? %>

      <li class="nav-item">
        <%= link_to new_user_session_path, class: 'nav-link' do %>
        Ingresar
        <span class="icon-login" aria-hidden="true"></span>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to new_user_registration_path, class: 'nav-link' do %>
        Registrarse
        <span class="icon-add-user" aria-hidden="true"></span>
        <% end %>
      </li>

      <% else %>

      <li class="nav-item">
        <%= link_to edit_user_registration_path, class: 'nav-link' do %>
        <%= current_user %>
        <span class="icon-user" aria-hidden="true"></span>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to cart_path, class: 'nav-link' do %>
        <span class="icon-cart" aria-hidden="true"></span>
        <%= current_user.carts.count %>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, data: { confirm: "Seguro que desea salir?" }, class: 'nav-link' do %>
        Salir
        <span class="icon-logout" aria-hidden="true"></span>
        <% end %>
      </li>
      <% end %>
    </ul>
    <%= form_tag products_path, method: :get, class: 'form-inline navbar-form pull-right m-r-md' do %>
    <div class="form-group">
      <%= text_field_tag :q, nil, placeholder: 'Search', class: 'form-control' %>
      <button type="submit" class="btn btn-success-outline">Submit</button>
    </div>
    <% end %>
  </div>
</nav>

app/views/shared/_footer.html.erb
<footer class="col-md-12 m-t-md">
		<div class="container">
			<div class="row">
				<div class="col-md-12 m-t-md m-b-md">
					<p class="text-center"><small><%= Date.new(2015).year %> &copy; SuperStore. Todos los derechos reservados.</small></p>
				</div>
			</div>
		</div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <div class="container">
    <a class="navbar-brand" href="#">SuperStore</a>
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <% if user_signed_in? && current_user.admin? %>
        <li class="nav-item">
          <%= link_to 'Admin', admin_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav pull-right">
      <% unless user_signed_in? %>

      <li class="nav-item">
        <%= link_to new_user_session_path, class: 'nav-link' do %>
        Ingresar
        <span class="icon-login" aria-hidden="true"></span>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to new_user_registration_path, class: 'nav-link' do %>
        Registrarse
        <span class="icon-add-user" aria-hidden="true"></span>
        <% end %>
      </li>

      <% else %>

      <li class="nav-item">
        <%= link_to edit_user_registration_path, class: 'nav-link' do %>
        <%= current_user %>
        <span class="icon-user" aria-hidden="true"></span>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to cart_path, class: 'nav-link' do %>
        <span class="icon-cart" aria-hidden="true"></span>
        <%= current_user.carts.count %>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, data: { confirm: "Seguro que desea salir?" }, class: 'nav-link' do %>
        Salir
        <span class="icon-logout" aria-hidden="true"></span>
        <% end %>
      </li>
      <% end %>
    </ul>
    <div class="form-inline navbar-form pull-right m-r-md">
    <div class="form-group">
      <%= text_field_tag :q, nil, placeholder: 'Burcar', class: 'form-control', 'data-behavior': 'search-products' %>
    </div>
    </div>
  </div>
</nav>