config/routes.rb
Rails.application.routes.draw do

  get 'locations/get_address'

  devise_for :users, skip: [:sessions, :registrations]

  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
    get    "users"   => "devise/registrations#edit",   as: :user_root
  end

  namespace :admin do
    get '/', to: 'pages#index'

    resources :products
    resources :users
    resources :orders, only: [:index, :show, :destroy]

  end

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create] do
      member do
        get 'like'
      end
    end

    member do
      get 'like'
      get 'add_to_cart'
    end
  end

  get 'cart', to: 'carts#show', as: 'cart'
  delete 'cart/:id', to: 'carts#destroy'

  get 'order', to: 'orders#create_order', as: 'create_order'
  get 'order/:id', to: 'orders#show', as: 'order'
  post 'order/:id', to: 'orders#paid_order', as: 'paid_order'
  delete 'order/:id', to: 'orders#cancel_order', as: 'cancel_order'

  get 'get_address', to: 'locations#get_address'

  root 'products#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base

  belongs_to :product
  belongs_to :user

  def self.quantity_of product
    p = find_by(product_id: product)
    p ? p.quantity : 0
  end


  def self.total
    total = 0
    find_each do |c|
      total += c.quantity * c.product.price
    end
    total
  end

  def subtotal
    self.product.price * self.quantity
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  load_and_authorize_resource

  def show
    user = User.find(current_user)
    @carts = user.carts
  end

  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Producto eliminado del carro' }
      format.json { head :no_content }
    end
  end

  private

    def set_cart
      @cart = Cart.find(params[:id])
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<tr>
	<th scope="row" class="text-center"><%= cart.product_id %></th>
  <td><%= image_tag cart.product.image.thumb.url, width: '50px' %></td>
  <td><%= link_to cart.product.name, cart.product %></td>
  <td class="text-center">
    <%= form_tag add_to_cart_product_path(cart.product), method: :get, class: 'form-inline' do |f| %>
      <div class="form-group">
        <%= number_field_tag :quantity, cart.quantity, min: 1, max: cart.product.stock , class: 'form-control', style: 'width: 60px; text-align: center' %>
      </div>
    <% end %>
  </td>
  <td class="text-right"><%= number_to_currency cart.product.price %></td>
  <td class="text-right"><%= number_to_currency cart.subtotal %></td>
  <td class="text-center"><%= link_to 'Eliminar', cart_path(cart), method: :delete, data: { confirm: 'Estas seguro?' } %></td>
</tr>

app/views/carts/show.html.erb
<h2 class="display-4 m-t-md m-b-md">Carro de compras</h2>

<hr>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th class="text-center">#</th>
      <th></th>
      <th>Name</th>
      <th class="text-center">Cantidad</th>
      <th class="text-right">Price</th>
      <th class="text-right">Subtotal</th>
      <th class="text-center">Eliminar</th>
    </tr>
  </thead>

  <tbody>
  	<%= render @carts %>
  	<tr class="table-footer">
  		<td colspan="5" class="text-right text-uppercase lead"><strong>Total:</strong></td>
  		<td class="text-right"><strong class="lead"><%= number_to_currency @carts.total %></strong></td>
  		<td class="text-center"><%= link_to 'Comprar', create_order_path, class: 'btn btn-success' %></td>
  	</tr>
  </tbody>
</table>

<hr>