config/routes.rb
Rails.application.routes.draw do

  get 'locations/get_address'

  devise_for :users, skip: [:sessions, :registrations]

  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
    get    "users"   => "devise/registrations#edit",   as: :user_root
  end

  namespace :admin do
    get '/', to: 'pages#index'

    resources :products
    resources :users
    resources :orders, only: [:index, :show, :destroy]

  end

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create] do
      member do
        get 'like'
      end
    end

    member do
      get 'like'
      get 'add_to_cart'
    end
  end

  get 'cart', to: 'carts#show', as: 'cart'
  delete 'cart/:id', to: 'carts#destroy'

  get 'order', to: 'orders#create_order', as: 'create_order'
  get 'order/:id', to: 'orders#show', as: 'order'
  post 'order/:id', to: 'orders#paid_order', as: 'paid_order'
  delete 'order/:id', to: 'orders#cancel_order', as: 'cancel_order'

  get 'get_address', to: 'locations#get_address'

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  include ApplicationHelper

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  mount_uploader :image, ImageUploader

  belongs_to :category

  has_many :product_orders
  has_many :orders, through: :product_orders

  has_many :carts
  has_many :users, through: :carts

  has_many :reviews, dependent: :destroy

  has_many :likes, as: :likable
  has_many :user_likes, through: :likes, source: :user

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true
  validates :stock, presence: true
  validates :category, presence: true

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude

  after_validation :geocode, if: ->(obj) { obj.address.present? and obj.address_changed? }

  after_validation :reverse_geocode, if: ->(obj) { (obj.latitude.present? && obj.longitude.present?) and (obj.latitude_changed? || obj.longitude_changed?) }


  default_scope { order(:id) }

  def update_stock (quantity)
    self.stock += quantity
    self.save
  end

    def slug_candidates
    [
      :name,
      [:name, :city],
      [:name, :street, :city],
      [:name, :street_number, :street, :city]
    ]
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :require_admin
  layout 'admin'

  # GET /admin/products
  # GET /admin/products.json
  def index
   if params[:q]
     @products = Product.where("lower(name) LIKE ?", "%#{params[:q].downcase}%")
   else
     @products = Product.all.includes(:category).order('categories.name', :id)
   end
  end

  # GET /admin/products/1
  # GET /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: admin_product_path(@product) }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1
  # PATCH/PUT /admin/products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: admin_product_path(@product) }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :price, :stock, :category_id, :image, :remove_image, :image_cache, :remote_image_url, :address, :latitude, :longitude)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
    if params[:q].present?
      @products = Product.where("lower(name) LIKE ?", "%#{params[:q].downcase}%")
    else
      @products = Product.all.includes(:category).page(1).per(6)
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @reviews = @product.reviews.reverse
  end

  def like
    @like = @product.likes.build(user: current_user)

    if @product.liked_by? current_user
      @product.remove_like current_user
      redirect_to @product, notice: 'Tu like a sido eliminado :('
    elsif @product.save
      redirect_to @product, notice: 'Gracias por tu like :D'
    else
      redirect_to @product, notice: 'Tu like no se ha guardado :('
    end
  end

  def add_to_cart
    quantity = params[:quantity] || 1
    cart = Cart.find_or_initialize_by(product_id: params[:id])
    cart.user = current_user if user_signed_in?
    cart.product = Product.find(params[:id])
    cart.quantity = quantity
    cart.save

    flash[:success] = 'Producto añadido a tu carro'
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="row">
  <%= form_for [:admin, @product], html: {class: 'col-md-6'} do |f| %>
  <% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
      <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Categoria' %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: 'Elije una Categoria'}, {class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 10, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :stock %><br>
    <%= f.number_field :stock, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %><br />
    <%= f.text_field :address, class: 'form-control js-address' %>
  </div>

  <div class="form-group">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude, class: 'form-control js-latitude' %>
  </div>

  <div class="form-group">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude, class: 'form-control js-longitude' %>
  </div>

  <div class="form-group">
    <p>
      <%= image_tag(@product.image.thumb.url, class: 'img-thumbnail') if @product.image? %>
      <% if @product.image? %>
      <label>
        <%= f.check_box :remove_image %>
        Remove Image
      </label>
      <% end %>
    </p>
    <%= f.hidden_field :image_cache %>
    <div class="input-group">
      <span class="input-group-btn">
        <span class="btn btn-primary btn-file">
          Browse&hellip; <%= f.file_field :image %>
        </span>
      </span>
      <input type="text" class="form-control" readonly>
    </div>
  </div>
  <div class="actions">
    <%= f.button class: 'btn btn-success' do %>
    Guardar
    <span class="glyphicon glyphicon-saved"></span>
    <% end %>
  </div>
  <% end %>
</div>

app/views/admin/products/_product.html.erb
<tr>
	<th scope="row"><%= product.id %></th>
  <td><%= product.name %></td>
  <td><%= truncate product.description %></td>
  <td><%= number_to_currency product.price %></td>
  <td><%= product.stock %></td>
  <td><%= product.category %></td>
  <td><%= product.likes.count %></td>
  <td><%= link_to 'Show', admin_product_path(product) %></td>
  <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
  <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/products/edit.html.erb
<h1 class="display-4 m-t-md m-b-md">Editing Product</h1>

<%= render 'form' %>

<hr>

<p class="m-t-md m-b-md">
<%= link_to @product, class: 'btn btn-warning' do %>
	  Ver
	  <span class="icon-eye" aria-hidden="true"></span>
	<% end %>

	<%= link_to products_path, class: 'btn btn-info' do %>
	  <span class="icon-back" aria-hidden="true"></span>
	  Volver
	<% end %>
</p>

app/views/admin/products/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Productos</h1>
</div>

<hr>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Stock</th>
      <th>Category</th>
      <th>Likes</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= render @products  %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1 class="display-4 m-t-md m-b-md">New Product</h1>

<%= render 'form' %>

<hr>

<p class="m-t-md m-b-md">
	<%= link_to admin_products_path, class: 'btn btn-info' do %>
	  <span class="icon-back" aria-hidden="true"></span>
	  Volver
	<% end %>
</p>

app/views/admin/products/show.html.erb
<p class="m-t-md m-b-md">
<%= link_to edit_admin_product_path(@product), class: 'btn btn-warning' do %>
	  Editar
	  <span class="icon-eye" aria-hidden="true"></span>
	<% end %>

	<%= link_to admin_products_path, class: 'btn btn-info' do %>
	  <span class="icon-back" aria-hidden="true"></span>
	  Volver
	<% end %>
</p>