config/routes.rb
Rails.application.routes.draw do

  get 'locations/get_address'

  devise_for :users, skip: [:sessions, :registrations]

  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session

    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
    get    "users"   => "devise/registrations#edit",   as: :user_root
  end

  namespace :admin do
    get '/', to: 'pages#index'

    resources :products
    resources :users
    resources :orders, only: [:index, :show, :destroy]

  end

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create] do
      member do
        get 'like'
      end
    end

    member do
      get 'like'
      get 'add_to_cart'
    end
  end

  get 'cart', to: 'carts#show', as: 'cart'
  delete 'cart/:id', to: 'carts#destroy'

  get 'order', to: 'orders#create_order', as: 'create_order'
  get 'order/:id', to: 'orders#show', as: 'order'
  post 'order/:id', to: 'orders#paid_order', as: 'paid_order'
  delete 'order/:id', to: 'orders#cancel_order', as: 'cancel_order'

  get 'get_address', to: 'locations#get_address'

  root 'products#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  before_save :default_role
  after_create :send_welcome_email
  after_update :send_password_change_email, if: :needs_password_change_email?

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :orders, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_many :carts, dependent: :destroy
  has_many :products, through: :carts

  has_many :likes
  has_many :product_likes, through: :likes, source: :likable, source_type: 'Product'
  has_many :review_likes, through: :likes, source: :likable, source_type: 'Review'

  validates :name, presence: true
  validates :lastname, presence: true
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validate :validate_username

  enum role: [:admin, :client, :guest]

  scope :order_by_role, -> { order(:role, :id) }

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude

  after_validation :geocode, if: ->(obj) { obj.address.present? and obj.address_changed? }
  after_validation :reverse_geocode, if: ->(obj) { (obj.latitude.present? && obj.longitude.present?) and (obj.latitude_changed? || obj.longitude_changed?) }

  def default_role
    self.role ||= 1
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def to_s
    "#{self.name} #{self.lastname}"
  end

  private

    def send_welcome_email
      UserMailer.welcome_email(self).deliver_later
    end

    def needs_password_change_email?
      encrypted_password_changed? && persisted?
    end

    def send_password_change_email
      UserMailer.password_changed(self).deliver_later(wait: 30.seconds)
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource
  before_action :require_admin
  layout 'admin'

  # GET /admin/users
  # GET /admin/users.json
  def index
    @users = User.order_by_role
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:admin_user]
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@admin_user) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
	<th scope="row"><%= user.id %></th>
  <td><%= user %></td>
  <td><%= user.email %></td>
  <td><%= user.role %></td>
  <td><%= link_to 'Show', admin_user_path(user) %></td>
  <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
  <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/users/edit.html.erb
<h1>Editing Admin User</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Usuarios</h1>
</div>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Typo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @users %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New Admin User</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>